[package]
name = "neversea-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["you"]

[dev-dependencies]

[dependencies.neversea]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.52.3"
